spring:
  elasticsearch:
    uris: http://192.168.80.129:9200
    connection-timeout: 1s
    socket-timeout: 30s
    username: 
    password: 

# Elasticsearch 配置说明
# uris: Elasticsearch 集群地址，支持多个节点
# connection-timeout: 连接超时时间
# socket-timeout: 数据传输超时时间
# username/password: 如果启用了安全认证，需要配置用户名密码